[package]
name = "typing-cars-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.typing-cars]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.56.1"
default-features = false
