// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           12
// Async Callback (empty):               1
// Total number of exported functions:  15

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    typing_cars
    (
        init => init
        upgrade => upgrade
        register_player => register_player
        update_profile => update_profile
        getPlayerProfile => get_player_profile
        getTotalPlayers => get_total_players
        createRace => create_race
        joinRace => join_race
        submitResult => submit_result
        finalizeRace => finalize_race
        cancelRace => cancel_race
        getRaceDetails => get_race_details
        getRaceResults => get_race_results
        getTotalRaces => get_total_races
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
